# Anki
deck_name=Japanese::TSC
model_name=JA-TSC
sentence_field=
image_field=
note_tag=subs2srs

# Menu
menu_font_size=24

# Clipboard
autoclip=yes
nuke_spaces=yes

# Anki browser
disable_gui_browse=yes

# Misc info
miscinfo_enable=no

# Secondary subs
secondary_sub_lang=eng,en

# Loudnorm
loudnorm=yes

# Audio
use_forvo=no
# Animated snapshot
animated_snapshot_height=300